// Realistic seed data used by the demo collector so the full pipeline
// (extraction -> cleaning -> validation -> dedup -> provenance -> export)
// can be demonstrated without depending on live external sites.

export const DEMO_JOB_LISTINGS = [
  { company_name: "NimbusAI Labs", role: "AI Engineering Intern", location: "Bangalore", salary: "₹40,000/month", posting_date: "2 days ago", application_url: "https://careers.nimbusai.example/jobs/1201", source_url: "https://careers.nimbusai.example/jobs/1201" },
  { company_name: "NimbusAI Labs", role: "AI Engineering Intern", location: "Bengaluru", salary: "₹40,000/month", posting_date: "2 days ago", application_url: "https://careers.nimbusai.example/jobs/1201?utm_source=linkedin", source_url: "https://boards.example.com/nimbusai/1201" },
  { company_name: "Verdant Systems", role: "Machine Learning Intern", location: "Hyderabad", salary: "₹35,000/month", posting_date: "1 day ago", application_url: "https://verdantsystems.example/careers/ml-intern-2026", source_url: "https://verdantsystems.example/careers/ml-intern-2026" },
  { company_name: "Kestrel Analytics", role: "Data Science Intern - AI", location: "Pune", salary: "₹30,000/month", posting_date: "4 days ago", application_url: "https://kestrelanalytics.example/jobs/ds-intern-ai", source_url: "https://kestrelanalytics.example/jobs/ds-intern-ai" },
  { company_name: "Orbital Cloud", role: "Backend Engineer Intern", location: "Gurugram", salary: "₹28,000/month", posting_date: "3 days ago", application_url: "https://orbitalcloud.example/careers/be-intern", source_url: "https://orbitalcloud.example/careers/be-intern" },
  { company_name: "Orbital Cloud", role: "Backend Engineering Intern", location: "Gurgaon", salary: "₹28,000/month", posting_date: "3 days ago", application_url: "https://orbitalcloud.example/careers/be-intern/", source_url: "https://jobsboard.example.com/orbital/be-intern" },
  { company_name: "Pixelforge Studio", role: "Generative AI Intern", location: "Remote", salary: "₹25,000/month", posting_date: "6 days ago", application_url: "https://pixelforge.example/careers/genai-intern", source_url: "https://pixelforge.example/careers/genai-intern" },
  { company_name: "Helion Robotics", role: "AI Research Intern", location: "Chennai", salary: "Not disclosed", posting_date: "5 days ago", application_url: "https://helionrobotics.example/jobs/ai-research", source_url: "https://helionrobotics.example/jobs/ai-research" },
  { company_name: "Meridian Fintech", role: "AI/ML Intern", location: "Mumbai", salary: "₹32,000/month", posting_date: "today", application_url: "https://meridianfintech.example/careers/aiml-intern", source_url: "https://meridianfintech.example/careers/aiml-intern" },
  { company_name: "Quanta Health", role: "AI Internship - Healthcare NLP", location: "Noida", salary: "₹38,000/month", posting_date: "1 day ago", application_url: "https://quantahealth.example/jobs/nlp-intern", source_url: "https://quantahealth.example/jobs/nlp-intern" },
  { company_name: "BrightPath Edtech", role: "AI Intern", location: "Delhi", salary: null, posting_date: "8 days ago", application_url: "https://brightpathedtech.example/careers/ai-intern", source_url: "https://brightpathedtech.example/careers/ai-intern" },
  { company_name: "Solstice Retail", role: "Backend Development Intern", location: "Bangalore", salary: "₹27,000/month", posting_date: "2 days ago", application_url: "", source_url: "https://solsticeretail.example/careers/backend-intern" },
  { company_name: "Ironclad Security", role: "AI-Powered Threat Detection Intern", location: "Pune", salary: "₹36,000/month", posting_date: "3 days ago", application_url: "https://ironcladsecurity.example/jobs/threat-ai", source_url: "https://ironcladsecurity.example/jobs/threat-ai" },
  { company_name: "Lumen Logistics", role: "AI Intern - Route Optimization", location: "Hyderabad", salary: "₹29,000/month", posting_date: "9 days ago", application_url: "https://lumenlogistics.example/careers/ai-route", source_url: "https://lumenlogistics.example/careers/ai-route" },
  { company_name: "Kestrel Analytics", role: "Data Science Intern (AI)", location: "Pune", salary: "₹30,000/month", posting_date: "4 days ago", application_url: "https://kestrelanalytics.example/jobs/ds-intern-ai?ref=twitter", source_url: "https://twitter.com/link/ds-intern-ai" },
  { company_name: "Vantage Cloud", role: "Software Engineer Intern - AI Tools", location: "Bangalore", salary: "₹34,000/month", posting_date: "2 days ago", application_url: "https://vantagecloud.example/careers/se-ai-tools", source_url: "https://vantagecloud.example/careers/se-ai-tools" },
  { company_name: "Arcadia Games", role: "AI Gameplay Intern", location: "Remote", salary: "₹26,000/month", posting_date: "1 day ago", application_url: "https://arcadiagames.example/jobs/ai-gameplay", source_url: "https://arcadiagames.example/jobs/ai-gameplay" },
  { company_name: "Solaris Energy", role: "AI Internship - Forecasting", location: "Chennai", salary: "₹31,000/month", posting_date: "7 days ago", application_url: "https://solarisenergy.example/careers/ai-forecast", source_url: "https://solarisenergy.example/careers/ai-forecast" },
];
